"""Build the ABEONA Crew Capsule engine and tanks in Onshape (HANDOFF_ONSHAPE.md).

Generates a FeatureScript feature from abeona/cad/engine_profile.csv and abeona/cad/layout.json,
uploads it to a Feature Studio in the document and inserts it into the Part Studio.
Auth: ONSHAPE_ACCESS_KEY / ONSHAPE_SECRET_KEY (HTTP Basic).

    python3 onshape/build_onshape.py            # write onshape/abeona_build.fs and push it
"""
import csv, json, math, os, sys
import requests

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
API = 'https://cad.onshape.com/api/v10'
DID, WID = 'ad9a6d4b75d67328be0a01a2', '3973cd08c6897a85595c46d7'
PS_EID = 'bb28d537a3204d397e59d9f9'      # Part Studio 1
FS_EID = '719f4110dafd39880531b4b0'      # Feature Studio "ABEONA build FS"
FS_VERSION = 3083

# Densities, kg/m^3. Liner/case/extension/tanks from the report scripts (s06, s09, config);
# injector 304L; head stack and COPVs are lumped to the report mass budget (s09).
RHO = dict(liner=1750.0, ti=4430.0, c103=8860.0, ss304=7900.0)
M_HEAD = 14.0 + 20.0 + 10.0              # valves + gimbal actuators + misc, kg (s09)
M_COPV = 379.9394503260619 / 4           # kg each (s09)
CAV_D, CAV_PITCH_R = 16.0, 100.0         # acoustic cavity bore and pitch radius, mm (assumed: not in the design data)

S = requests.Session()
S.auth = (os.environ['ONSHAPE_ACCESS_KEY'], os.environ['ONSHAPE_SECRET_KEY'])
S.headers.update({'Accept': 'application/json;charset=UTF-8; qs=0.09', 'Content-Type': 'application/json'})


def api(method, path, **kw):
    r = S.request(method, API + path, **kw)
    if not r.ok:
        sys.exit(f'{method} {path} -> {r.status_code}: {r.text[:800]}')
    return r.json()


def outlines():
    lay = json.load(open(os.path.join(ROOT, 'abeona/cad/layout.json')))
    rows = [dict(x=float(r['x_mm']), ri=float(r['r_inner_mm']), ro=float(r['r_outer_mm']), reg=r['region'])
            for r in csv.DictReader(open(os.path.join(ROOT, 'abeona/cad/engine_profile.csv')))]
    e = lay['engine']
    zt, tl, te = e['throat_z'], e['liner_thickness'], e['extension_thickness']
    abl = [r for r in rows if r['reg'] == 'ablative']
    ext = [abl[-1]] + [r for r in rows if r['reg'] == 'C103_extension']   # start at the interface station
    z = lambda r: zt - r['x']
    liner = [(r['ri'], z(r)) for r in abl] + [(r['ri'] + tl, z(r)) for r in reversed(abl)]
    case = [(r['ri'] + tl, z(r)) for r in abl] + [(r['ro'], z(r)) for r in reversed(abl)]
    nozext = [(r['ri'], z(r)) for r in ext] + [(r['ri'] + te, z(r)) for r in reversed(ext)]
    return lay, liner, case, nozext


def fs_pts(pts):
    return '[' + ', '.join(f'[{r:.4f}, {z:.4f}]' for r, z in pts) + ']'


def featurescript():
    lay, liner, case, nozext = outlines()
    e, sm = lay['engine'], lay['service_module']
    rc = e['chamber_dia'] / 2
    z_face, z_gim = e['injector_face_z'], e['gimbal_plane_z']
    z_plate = z_face + e['injector_thickness']
    cav_depth = e['acoustic_cavities']['depth']
    n_cav = e['acoustic_cavities']['n']
    # lumped densities from the report mass budget
    v_cav_head = n_cav * math.pi * (CAV_D / 2) ** 2 * max(0.0, cav_depth - e['injector_thickness'])
    v_head = (math.pi * rc ** 2 * (z_gim - z_plate) - v_cav_head) * 1e-9
    rho_head = M_HEAD / v_head
    he = lay['helium_bottles']
    rho_copv = M_COPV / (math.pi / 6 * (he['dia'] * 1e-3) ** 3)
    R, H, Hc = sm['diameter'] / 2, sm['length'], sm['aft_cone_height']
    envelope = [(0.0, -Hc), (200.0, -Hc), (R, 0.0), (R, H), (0.0, H)]   # aft cone to 0.2 m radius (s12 layout figure)
    tanks = '\n'.join(
        f'        shell(context, id + "{k}", {t["center_z"]:.4f}, {t["inner_dia"] / 2:.4f}, {t["inner_dia"] / 2 + t["wall"]:.4f}, '
        f'"Tank - {lbl} (Ti-6Al-4V)", material("Ti-6Al-4V", {RHO["ti"]} * kilogram / meter ^ 3), {col});'
        for k, lbl, col in (('tankNTO', 'NTO', 'color(0.85, 0.45, 0.2)'), ('tankMMH', 'MMH', 'color(0.3, 0.6, 0.85)'))
        for t in [lay['tank_' + lbl]])
    return f'''FeatureScript {FS_VERSION};
import(path : "onshape/std/common.fs", version : "{FS_VERSION}.0");

// Generated by onshape/build_onshape.py from abeona/cad/engine_profile.csv and layout.json. Units mm,
// service-module frame: origin at the SM base on the axis, +Z up. Profiles are (r, z) outlines.
const LINER = {fs_pts(liner)};
const CASE = {fs_pts(case)};
const EXTENSION = {fs_pts(nozext)};
const ENVELOPE = {fs_pts(envelope)};

function revolveOutline(context is Context, id is Id, pts is array) returns Query
{{
    const sk = newSketchOnPlane(context, id + "sk", {{ "sketchPlane" : plane(vector(0, 0, 0) * millimeter, vector(0, -1, 0), vector(1, 0, 0)) }});
    var p = [];
    for (var q in pts)
        p = append(p, vector(q[0], q[1]) * millimeter);
    p = append(p, p[0]);
    skPolyline(sk, "outline", {{ "points" : p }});
    skSolve(sk);
    opRevolve(context, id + "rev", {{ "entities" : qSketchRegion(id + "sk"), "axis" : line(vector(0, 0, 0) * millimeter, vector(0, 0, 1)),
                "angleForward" : 2 * PI * radian }});
    opDeleteBodies(context, id + "del", {{ "entities" : qCreatedBy(id + "sk") }});
    return qCreatedBy(id + "rev", EntityType.BODY);
}}

function tag(context is Context, bodies is Query, name is string, mat, col is Color)
{{
    setProperty(context, {{ "entities" : bodies, "propertyType" : PropertyType.NAME, "value" : name }});
    if (mat != undefined)
        setProperty(context, {{ "entities" : bodies, "propertyType" : PropertyType.MATERIAL, "value" : mat }});
    setProperty(context, {{ "entities" : bodies, "propertyType" : PropertyType.APPEARANCE, "value" : col }});
}}

function shell(context is Context, id is Id, zc is number, ri is number, ro is number, name is string, mat, col is Color)
{{
    opSphere(context, id + "outer", {{ "center" : vector(0, 0, zc) * millimeter, "radius" : ro * millimeter }});
    opSphere(context, id + "inner", {{ "center" : vector(0, 0, zc) * millimeter, "radius" : ri * millimeter }});
    opBoolean(context, id + "hollow", {{ "tools" : qCreatedBy(id + "inner", EntityType.BODY), "targets" : qCreatedBy(id + "outer", EntityType.BODY),
                "operationType" : BooleanOperationType.SUBTRACTION }});
    tag(context, qCreatedBy(id + "outer", EntityType.BODY), name, mat, col);
}}

annotation {{ "Feature Type Name" : "ABEONA engine and tanks" }}
export const abeonaBuild = defineFeature(function(context is Context, id is Id, definition is map)
    precondition
    {{
    }}
    {{
        // 1. Engine
        tag(context, revolveOutline(context, id + "liner", LINER), "Engine - Ablative liner (silica phenolic)",
            material("Silica phenolic", {RHO["liner"]} * kilogram / meter ^ 3), color(0.45, 0.35, 0.3));
        tag(context, revolveOutline(context, id + "case", CASE), "Engine - Chamber case (Ti-6Al-4V)",
            material("Ti-6Al-4V", {RHO["ti"]} * kilogram / meter ^ 3), color(0.7, 0.7, 0.75));
        tag(context, revolveOutline(context, id + "ext", EXTENSION), "Engine - Nozzle extension (C-103)",
            material("C-103 niobium", {RHO["c103"]} * kilogram / meter ^ 3), color(0.35, 0.35, 0.4));
        fCylinder(context, id + "plate", {{ "bottomCenter" : vector(0, 0, {z_face:.4f}) * millimeter, "topCenter" : vector(0, 0, {z_plate:.4f}) * millimeter,
                    "radius" : {rc:.4f} * millimeter }});
        fCylinder(context, id + "head", {{ "bottomCenter" : vector(0, 0, {z_plate:.4f}) * millimeter, "topCenter" : vector(0, 0, {z_gim:.4f}) * millimeter,
                    "radius" : {rc:.4f} * millimeter }});
        var cavs = [];
        for (var i = 0; i < {n_cav}; i += 1)
        {{
            const a = (15 + 360 * i / {n_cav}) * degree;
            fCylinder(context, id + ("cav" ~ i), {{ "bottomCenter" : vector({CAV_PITCH_R} * cos(a), {CAV_PITCH_R} * sin(a), {z_face:.4f}) * millimeter,
                        "topCenter" : vector({CAV_PITCH_R} * cos(a), {CAV_PITCH_R} * sin(a), {z_face + cav_depth:.4f}) * millimeter,
                        "radius" : {CAV_D / 2} * millimeter }});
            cavs = append(cavs, qCreatedBy(id + ("cav" ~ i), EntityType.BODY));
        }}
        opBoolean(context, id + "cavities", {{ "tools" : qUnion(cavs),
                    "targets" : qUnion([qCreatedBy(id + "plate", EntityType.BODY), qCreatedBy(id + "head", EntityType.BODY)]),
                    "operationType" : BooleanOperationType.SUBTRACTION }});
        tag(context, qCreatedBy(id + "plate", EntityType.BODY), "Engine - Injector plate (304L, 12 acoustic cavities)",
            material("304L stainless", {RHO["ss304"]} * kilogram / meter ^ 3), color(0.8, 0.8, 0.82));
        tag(context, qCreatedBy(id + "head", EntityType.BODY), "Engine - Head/valve/gimbal stack (lumped {M_HEAD:.0f} kg)",
            material("Lumped head stack", {rho_head:.3f} * kilogram / meter ^ 3), color(0.55, 0.55, 0.6));

        // 2. Tanks
{tanks}
        for (var i = 0; i < {he['n']}; i += 1)
        {{
            const ang = {he['angles_deg']}[i];
            const a = ang * degree;
            opSphere(context, id + ("copv" ~ i), {{ "center" : vector({he['center_radius']:.4f} * cos(a), {he['center_radius']:.4f} * sin(a), {he['center_z']:.4f}) * millimeter,
                        "radius" : {he['dia'] / 2:.4f} * millimeter }});
            tag(context, qCreatedBy(id + ("copv" ~ i), EntityType.BODY), "COPV - He " ~ (i + 1) ~ " (" ~ ang ~ " deg, lumped {M_COPV:.1f} kg)",
                material("Lumped COPV", {rho_copv:.4f} * kilogram / meter ^ 3), color(0.2, 0.2, 0.2));
        }}

        // 3. Envelope (reference only, no material)
        tag(context, revolveOutline(context, id + "env", ENVELOPE), "REF - Service module envelope", undefined, color(0.6, 0.75, 0.95, 0.15));
    }});
'''


if __name__ == '__main__':
    code = featurescript()
    open(os.path.join(ROOT, 'onshape/abeona_build.fs'), 'w').write(code)
    if '--no-push' in sys.argv:
        sys.exit()
    cur = api('GET', f'/featurestudios/d/{DID}/w/{WID}/e/{FS_EID}')
    api('POST', f'/featurestudios/d/{DID}/w/{WID}/e/{FS_EID}',
        json=dict(contents=code, serializationVersion=cur['serializationVersion'], sourceMicroversion=cur['sourceMicroversion']))
    specs = api('GET', f'/featurestudios/d/{DID}/w/{WID}/e/{FS_EID}/featurespecs')
    print('feature specs:', [s.get('featureType') for s in specs.get('featureSpecs', [])])
    mv = next(el['microversionId'] for el in api('GET', f'/documents/d/{DID}/w/{WID}/elements') if el['id'] == FS_EID)
    feats = api('GET', f'/partstudios/d/{DID}/w/{WID}/e/{PS_EID}/features')
    old = [f['message'] for f in feats['features'] if f['message'].get('featureType') == 'abeonaBuild']
    feature = dict(btType='BTMFeature-134', featureType='abeonaBuild', name='ABEONA engine and tanks',
                   namespace=f'e{FS_EID}::m{mv}', parameters=[])
    body = dict(feature=feature, serializationVersion=feats['serializationVersion'], sourceMicroversion=feats['sourceMicroversion'])
    if old:
        feature['featureId'] = old[0]['featureId']
        res = api('POST', f'/partstudios/d/{DID}/w/{WID}/e/{PS_EID}/features/featureid/{old[0]["featureId"]}', json=body)
    else:
        res = api('POST', f'/partstudios/d/{DID}/w/{WID}/e/{PS_EID}/features', json=body)
    print('feature state:', res.get('featureState'))
